bibliography: ref.bib
format: 
  revealjs:
    theme: [default, custom_theme.scss]
    css: tachyons-minimal.css
    width: 1600
    height: 900
    html-math-method: mathjax
    slide-number: true
    fig-format: png
    fig-align: center
    # fig-width: 3.33
    # fig-height: 1
    scrollable: false
    history: false
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: wrap
    lang: en-CA
execute: 
  echo: false
  warning: false
  
knitr:
  opts_chunk:
    message: FALSE
    dev: "png"
    fig.align: center
    fig.path: "figures/"

editor: source